FROM python3.8

RUN apt update & apt upgrade

